// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Widget$ReactHooksTemplate = require("./Widget.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Widget$ReactHooksTemplate.make, { }), "index1");

/*  Not a pure module */
